# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginGitHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift', '~> 4'
    pod 'RxCocoa', '~> 4'

  target 'LoginGitHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginGitHubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
